export const firstRound = [
  "Bad planning",
  "Parking lot full",
  "Car fire (again)",
  "Desk reservation wars",
  "Conference room double-booked",
  // "Desk hoteling app down",
  "Shuttle roulette",
  "Teams: “you're on mute”",
  "Calendar ping-pong",
  "Circle back",
  "Low-hanging fruit",
  "Touch base offline",
  "Deep dive on nothing",
  "Synergy alignment",
  "KPI realignment",
  "OKR rewrite mid-quarter",
  "Reorg bingo",
  "Mandatory fun event",
  "Town hall (no Q&A)",
  "Leadership email: “We're a family”",
  "Do more with less",
  "Budget freeze (again)",
  "Headcount freeze, workload +20%",
  "Tech debt is “risk” now",
  "Audit readiness fire drill",
  "Controls uplift-a-thon",
  "SOX says no",
  "Change freeze extension",
  "VPN flakeout",
  "Wi-Fi roulette",
  "Badge reader offline",
  "Elevator out of service",
  "Fire alarm test (again)",
  "HVAC: arctic mode",
  "Coffee machine down",
  "Free pizza as thanks",
  "Warm breakroom soda",
  "Monitor/dock shortage",
  "Ergonomic chairs MIA",
  "Quiet room booked for meeting",
  "Accessibility ignored (again)",
  "“Per my last email…”",
  "“Who owns this?”",
  "Escalate to leadership",
  "Parking validation saga",
  "Phishing test gotcha",
  "DLP blocked harmless file",
  "Risk appetite shifted",
  "Cloud migration wave 17",
  "Resiliency test during release",
  "Sunday night deploy surprise",
  "On-call without coverage",
  "Pager went off in meeting",
  "“Above my pay grade”",
  "“Let's take that offline”",
  "“One more slide”",
  "2% merit raise (lol)",
  "RTO pep talk",
  "Five days, zero desks",
  "Mall traffic gridlock",
  "Union Strong",
  "Solidarity Forever",
  "Respect us, protect us",
  "Bargaining works",
  "Nothing about us without us",
  "We are the union",
  "Safe staffing, sane scheduling",
  "RTO? Let's talk contract",
  "Coworker fired up (literally)",
  "Pre-mortem already happening",
  "Parking lot smoke check",
  "“Working as intended”",
  "This is fine (dog)",
  "Seagull management",
  "Spreadsheet heroics",
  "“It's on the roadmap”",
  "“Single-threaded owner”",
  "“Need a quick win”",
  "Shadow IT saves the day",
  "Ticket closed, problem persists",
  "“Out of scope”",
  "“Not my OKR”",
  "“We'll socialize it”",
  "“Data-driven decision”",
  "“Future state”",
  "“North star”",
  "“Best-in-class”",
  "“World-class”",
  "Blameless postmortem (with blame)",
  "Lessons learned… again"
] as const