// Bingo items for Chase/JPMC themed bingo cards
export const bingoItems = [
  "RTO announcement",
  "Pizza party",
  "We're like a family",
  "Record profits",
  "Cost cutting measures",
  "Mandatory training",
  "Team building exercise",
  "Performance review",
  "Budget constraints",
  "Market conditions",
  "Industry standard",
  "Competitive analysis",
  "Strategic initiative",
  "Process improvement",
  "Change management",
  "Stakeholder alignment",
  "Best practices",
  "Innovation focus",
  "Customer centric",
  "Data driven",
  "Agile methodology",
  "Lean principles",
  "Continuous improvement",
  "Synergy opportunities",
  "Value proposition",
  "Jamie Dimon quote",
  "Chase logo everywhere",
  "Banking regulations",
  "Compliance training",
  "Risk management",
  "Audit findings",
  "Regulatory pressure",
  "Customer complaints",
  "System downtime",
  "Legacy technology",
  "Digital transformation",
  "Mobile app issues",
  "Branch closures",
  "ATM problems",
  "Credit card fees",
  "Overdraft charges",
  "Loan processing delays",
  "Mortgage rate changes",
  "Investment advice",
  "Wealth management",
  "Private banking",
  "Corporate banking",
  "Investment banking",
  "Trading floor",
  "Market volatility",
  "Interest rate changes",
  "Federal Reserve",
  "FDIC insurance",
  "Bank stress tests",
  "Capital requirements",
  "Liquidity ratios",
  "Credit ratings",
  "Stock price fluctuations",
  "Earnings calls",
  "Quarterly reports",
  "Annual meetings",
  "Proxy voting",
  "Shareholder activism",
  "Executive compensation",
  "Golden parachutes",
  "Layoff rumors",
  "Hiring freezes",
  "Bonus cuts",
  "Salary freezes",
  "Benefits changes",
  "Healthcare costs",
  "Retirement plans",
  "401k matching",
  "Stock options",
  "ESPP program",
  "Employee stock",
  "Vesting schedules",
  "Non-compete clauses",
  "Arbitration agreements",
  "Class action lawsuits",
  "Whistleblower complaints",
  "SEC investigations",
  "DOJ settlements",
  "Regulatory fines",
  "Consent orders",
  "Cease and desist",
  "Compliance monitoring",
  "Internal audits",
  "External audits",
  "SOX compliance",
  "GLBA compliance",
  "CCPA compliance",
  "GDPR compliance",
  "Data breaches",
  "Cybersecurity threats",
  "Phishing attempts",
  "Ransomware attacks",
  "Identity theft",
  "Fraud detection",
  "Money laundering",
  "KYC procedures",
  "AML compliance",
  "Sanctions screening",
  "OFAC lists",
  "Terrorist financing",
  "Corruption prevention",
  "Bribery laws",
  "FCPA compliance",
  "Anti-trust concerns",
  "Market manipulation",
  "Insider trading",
  "Front running",
  "Wash trading",
  "Spoofing",
  "Market making",
  "Proprietary trading",
  "Volcker Rule",
  "Dodd-Frank",
  "Basel III",
  "Stress testing",
  "Living wills",
  "Resolution planning",
  "Too big to fail",
  "Systemic risk",
  "Financial stability",
  "Macroeconomic factors",
  "Inflation concerns",
  "Recession fears",
  "Economic indicators",
  "GDP growth",
  "Unemployment rates",
  "Consumer confidence",
  "Business sentiment",
  "Supply chain issues",
  "Labor shortages",
  "Wage inflation",
  "Cost of living",
  "Housing market",
  "Commercial real estate",
  "Office vacancies",
  "Remote work trends",
  "Hybrid work models",
  "Return to office",
  "Commute times",
  "Public transportation",
  "Parking costs",
  "Childcare expenses",
  "Healthcare premiums",
  "Deductible increases",
  "Prescription costs",
  "Mental health support",
  "Wellness programs",
  "Gym memberships",
  "Healthy food options",
  "Work-life balance",
  "Burnout prevention",
  "Stress management",
  "Employee assistance",
  "Counseling services",
  "Legal assistance",
  "Financial planning",
  "Tax preparation",
  "Estate planning",
  "Insurance coverage",
  "Disability benefits",
  "Life insurance",
  "Accident insurance",
  "Travel insurance",
  "Pet insurance",
  "Home insurance",
  "Auto insurance",
  "Umbrella policies",
  "Professional liability",
  "Directors and officers",
  "Errors and omissions",
  "Cyber liability",
  "Business interruption",
  "Property damage",
  "Natural disasters",
  "Climate change",
  "ESG initiatives",
  "Sustainability goals",
  "Carbon footprint",
  "Renewable energy",
  "Green buildings",
  "Electric vehicles",
  "Public transit",
  "Bike sharing",
  "Carpool programs",
  "Vanpool services",
  "Shuttle buses",
  "Subsidized parking",
  "Transit passes",
  "Bike storage",
  "Shower facilities",
  "Locker rooms",
  "Changing rooms",
  "Nursing rooms",
  "Prayer rooms",
  "Quiet spaces",
  "Collaboration areas",
  "Meeting rooms",
  "Conference rooms",
  "Training rooms",
  "Break rooms",
  "Kitchen facilities",
  "Coffee machines",
  "Vending machines",
  "Cafeteria services",
  "Food trucks",
  "Local restaurants",
  "Delivery services",
  "Catering options",
  "Happy hours",
  "Team lunches",
  "Company events",
  "Holiday parties",
  "Summer picnics",
  "Golf outings",
  "Baseball games",
  "Basketball games",
  "Football games",
  "Hockey games",
  "Soccer matches",
  "Tennis tournaments",
  "Running clubs",
  "Fitness challenges",
  "Weight loss programs",
  "Smoking cessation",
  "Alcohol awareness",
  "Drug testing",
  "Background checks",
  "Credit checks",
  "Reference checks",
  "Employment verification",
  "Education verification",
  "License verification",
  "Certification requirements",
  "Continuing education",
  "Professional development",
  "Skills training",
  "Leadership development",
  "Management training",
  "Communication skills",
  "Presentation skills",
  "Negotiation skills",
  "Conflict resolution",
  "Diversity training",
  "Inclusion training",
  "Unconscious bias",
  "Harassment prevention",
  "Discrimination prevention",
  "Equal opportunity",
  "Affirmative action",
  "Veterans programs",
  "Disability accommodations",
  "Religious accommodations",
  "Medical accommodations",
  "Pregnancy accommodations",
  "Lactation support",
  "Parental leave",
  "Maternity leave",
  "Paternity leave",
  "Adoption leave",
  "Foster care leave",
  "Bereavement leave",
  "Jury duty leave",
  "Military leave",
  "Voting leave",
  "Volunteer time",
  "Community service",
  "Charitable giving",
  "Matching gifts",
  "United Way",
  "Blood drives",
  "Food drives",
  "Toy drives",
  "Clothing drives",
  "Book drives",
  "School supplies",
  "Backpack programs",
  "Scholarship programs",
  "Internship programs",
  "Apprenticeship programs",
  "Mentorship programs",
  "Buddy programs",
  "Onboarding process",
  "Orientation sessions",
  "Welcome packages",
  "Swag bags",
  "Company merchandise",
  "Logo items",
  "Branded clothing",
  "Business cards",
  "Name tags",
  "ID badges",
  "Access cards",
  "Parking permits",
  "Building access",
  "Floor access",
  "Elevator access",
  "Stairwell access",
  "Emergency exits",
  "Fire alarms",
  "Sprinkler systems",
  "Security cameras",
  "Guard stations",
  "Metal detectors",
  "Bag checks",
  "Visitor badges",
  "Guest passes",
  "Contractor badges",
  "Vendor access",
  "Delivery access",
  "Loading docks",
  "Service elevators",
  "Freight elevators",
  "Handicap access",
  "Wheelchair ramps",
  "Accessible parking",
  "Accessible restrooms",
  "Accessible workstations",
  "Ergonomic chairs",
  "Standing desks",
  "Treadmill desks",
  "Bike desks",
  "Exercise balls",
  "Footrests",
  "Wrist rests",
  "Monitor stands",
  "Keyboard trays",
  "Mouse pads",
  "Desk lamps",
  "Task lighting",
  "Natural light",
  "Window views",
  "Air quality",
  "Temperature control",
  "Humidity control",
  "Ventilation systems",
  "Air filtration",
  "HEPA filters",
  "UV sterilization",
  "Ionization systems",
  "Ozone generators",
  "Humidifiers",
  "Dehumidifiers",
  "Air purifiers",
  "Plants",
  "Living walls",
  "Green roofs",
  "Rooftop gardens",
  "Outdoor spaces",
  "Patios",
  "Balconies",
  "Terraces",
  "Courtyards",
  "Plazas",
  "Walkways",
  "Bike paths",
  "Jogging trails",
  "Fitness centers",
  "Gym equipment",
  "Cardio machines",
  "Weight machines",
  "Free weights",
  "Yoga studios",
  "Pilates rooms",
  "Dance studios",
  "Basketball courts",
  "Tennis courts",
  "Racquetball courts",
  "Squash courts",
  "Volleyball courts",
  "Badminton courts",
  "Table tennis",
  "Pool tables",
  "Foosball tables",
  "Air hockey",
  "Arcade games",
  "Video games",
  "Board games",
  "Puzzle rooms",
  "Escape rooms",
  "Game rooms",
  "Lounge areas",
  "Comfortable seating",
  "Bean bag chairs",
  "Hammocks",
  "Nap pods",
  "Sleep rooms",
  "Meditation rooms",
  "Prayer rooms",
  "Reflection spaces",
  "Quiet zones",
  "Noise reduction",
  "Sound masking",
  "White noise",
  "Music systems",
  "Headphones",
  "Earplugs",
  "Eye masks",
  "Neck pillows",
  "Blankets",
  "Towels",
  "Shower supplies",
  "Hair dryers",
  "Irons",
  "Ironing boards",
  "Shoe shine",
  "Dry cleaning",
  "Laundry service",
  "Mail service",
  "Package delivery",
  "Concierge service",
  "Travel booking",
  "Hotel reservations",
  "Car rentals",
  "Airline tickets",
  "Train tickets",
  "Bus passes",
  "Taxi vouchers",
  "Ride sharing",
  "Car sharing",
  "Bike sharing",
  "Scooter sharing",
  "Parking apps",
  "Transit apps",
  "Navigation apps",
  "Weather apps",
  "News apps",
  "Social media",
  "Professional networks",
  "Industry groups",
  "Trade associations",
  "Professional societies",
  "Certification bodies",
  "Accreditation agencies",
  "Regulatory bodies",
  "Government agencies",
  "Federal agencies",
  "State agencies",
  "Local agencies",
  "Municipal offices",
  "County offices",
  "City offices",
  "Town offices",
  "Village offices",
  "School districts",
  "Universities",
  "Colleges",
  "Community colleges",
  "Technical schools",
  "Vocational schools",
  "Apprenticeship programs",
  "Training programs",
  "Development programs",
  "Leadership programs",
  "Management programs",
  "Executive programs",
  "MBA programs",
  "Graduate programs",
  "Undergraduate programs",
  "Certificate programs",
  "Diploma programs",
  "Degree programs",
  "Online programs",
  "Hybrid programs",
  "In-person programs",
  "Virtual programs",
  "Remote programs",
  "Distance learning",
  "E-learning",
  "Digital learning",
  "Blended learning",
  "Flipped classrooms",
  "Active learning",
  "Experiential learning",
  "Hands-on learning",
  "Project-based learning",
  "Problem-based learning",
  "Case-based learning",
  "Scenario-based learning",
  "Simulation-based learning",
  "Game-based learning",
  "Gamification",
  "Points systems",
  "Badge systems",
  "Leaderboards",
  "Achievements",
  "Rewards",
  "Recognition",
  "Awards",
  "Trophies",
  "Plaques",
  "Certificates",
  "Diplomas",
  "Degrees",
  "Licenses",
  "Permits",
  "Credentials",
  "Qualifications",
  "Competencies",
  "Skills",
  "Abilities",
  "Talents",
  "Strengths",
  "Weaknesses",
  "Opportunities",
  "Threats",
  "SWOT analysis",
  "PEST analysis",
  "Porter's Five Forces",
  "Value chain analysis",
  "Competitive analysis",
  "Market analysis",
  "Industry analysis",
  "Trend analysis",
  "Forecasting",
  "Predictive modeling",
  "Statistical analysis",
  "Data mining",
  "Machine learning",
  "Artificial intelligence",
  "Deep learning",
  "Neural networks",
  "Natural language processing",
  "Computer vision",
  "Robotics",
  "Automation",
  "Process automation",
  "Workflow automation",
  "Business process automation",
  "Robotic process automation",
  "Intelligent automation",
  "Cognitive automation",
  "Hyperautomation",
  "Digital transformation",
  "Digitalization",
  "Digitization",
  "Cloud computing",
  "Software as a service",
  "Platform as a service",
  "Infrastructure as a service",
  "Function as a service",
  "Serverless computing",
  "Edge computing",
  "Fog computing",
  "Grid computing",
  "Distributed computing",
  "Parallel computing",
  "Quantum computing",
  "Blockchain",
  "Cryptocurrency",
  "Bitcoin",
  "Ethereum",
  "Smart contracts",
  "DeFi",
  "NFTs",
  "Web3",
  "Metaverse",
  "Virtual reality",
  "Augmented reality",
  "Mixed reality",
  "Extended reality",
  "3D printing",
  "Additive manufacturing",
  "Internet of Things",
  "IoT devices",
  "Smart devices",
  "Connected devices",
  "Wearable technology",
  "Fitness trackers",
  "Smart watches",
  "Smart glasses",
  "Smart clothing",
  "Smart homes",
  "Smart buildings",
  "Smart cities",
  "Smart grids",
  "Smart transportation",
  "Autonomous vehicles",
  "Self-driving cars",
  "Electric vehicles",
  "Hybrid vehicles",
  "Fuel cell vehicles",
  "Hydrogen vehicles",
  "Solar vehicles",
  "Wind vehicles",
  "Tidal vehicles",
  "Geothermal energy",
  "Nuclear energy",
  "Fossil fuels",
  "Renewable energy",
  "Clean energy",
  "Green energy",
  "Sustainable energy",
  "Carbon neutral",
  "Carbon negative",
  "Carbon positive",
  "Carbon footprint",
  "Carbon offset",
  "Carbon trading",
  "Carbon tax",
  "Carbon pricing",
  "Carbon capture",
  "Carbon storage",
  "Carbon sequestration",
  "Climate change",
  "Global warming",
  "Greenhouse gases",
  "Emissions",
  "Pollution",
  "Air pollution",
  "Water pollution",
  "Soil pollution",
  "Noise pollution",
  "Light pollution",
  "Thermal pollution",
  "Radioactive pollution",
  "Plastic pollution",
  "Microplastics",
  "Ocean pollution",
  "Marine pollution",
  "Atmospheric pollution",
  "Indoor pollution",
  "Outdoor pollution",
  "Environmental impact",
  "Ecological footprint",
  "Biodiversity",
  "Species extinction",
  "Habitat loss",
  "Deforestation",
  "Desertification",
  "Soil erosion",
  "Water scarcity",
  "Food security",
  "Energy security",
  "National security",
  "Economic security",
  "Social security",
  "Financial security",
  "Job security",
  "Health security",
  "Digital security",
  "Cybersecurity",
  "Information security",
  "Data security",
  "Network security",
  "Application security",
  "Cloud security",
  "Mobile security",
  "IoT security",
  "Endpoint security",
  "Perimeter security",
  "Zero trust",
  "Identity management",
  "Access control",
  "Authentication",
  "Authorization",
  "Single sign-on",
  "Multi-factor authentication",
  "Biometric authentication",
  "Fingerprint scanning",
  "Facial recognition",
  "Voice recognition",
  "Iris scanning",
  "Retina scanning",
  "Palm scanning",
  "Vein scanning",
  "Gait analysis",
  "Behavioral biometrics",
  "Keystroke dynamics",
  "Mouse dynamics",
  "Touch dynamics",
  "Device fingerprinting",
  "Browser fingerprinting",
  "Canvas fingerprinting",
  "Audio fingerprinting",
  "Video fingerprinting",
  "Font fingerprinting",
  "Plugin fingerprinting",
  "Screen resolution",
  "Color depth",
  "Time zone",
  "Language settings",
  "Keyboard layout",
  "Operating system",
  "Browser version",
  "Device type",
  "Device model",
  "Manufacturer",
  "Serial number",
  "MAC address",
  "IP address",
  "Geolocation",
  "GPS coordinates",
  "Cell tower triangulation",
  "WiFi positioning",
  "Bluetooth positioning",
  "NFC positioning",
  "RFID tracking",
  "Barcode scanning",
  "QR code scanning",
  "NFC tags",
  "RFID tags",
  "Smart cards",
  "Contactless cards",
  "Chip cards",
  "Magnetic stripe cards",
  "EMV cards",
  "Contactless payments",
  "Mobile payments",
  "Digital wallets",
  "Apple Pay",
  "Google Pay",
  "Samsung Pay",
  "PayPal",
  "Venmo",
  "Zelle",
  "Square Cash",
  "Cash App",
  "Stripe",
  "Square",
  "PayPal Here",
  "Square Reader",
  "Card readers",
  "Point of sale",
  "POS systems",
  "Cash registers",
  "Barcode scanners",
  "Receipt printers",
  "Cash drawers",
  "Credit card terminals",
  "Debit card terminals",
  "Gift card terminals",
  "Loyalty card terminals",
  "Membership card terminals",
  "Access card terminals",
  "ID card terminals",
  "Driver's license scanners",
  "Passport scanners",
  "Document scanners",
  "Check scanners",
  "Money counters",
  "Coin counters",
  "Bill counters",
  "Currency detectors",
  "Counterfeit detectors",
  "UV lights",
  "Magnifying glasses",
  "Microscopes",
  "Spectrometers",
  "X-ray machines",
  "CT scanners",
  "MRI machines",
  "Ultrasound machines",
  "EKG machines",
  "Blood pressure monitors",
  "Thermometers",
  "Pulse oximeters",
  "Glucose monitors",
  "Insulin pumps",
  "Pacemakers",
  "Defibrillators",
  "Ventilators",
  "Dialysis machines",
  "Chemotherapy machines",
  "Radiation therapy",
  "Surgical robots",
  "Da Vinci robots",
  "Telemedicine",
  "Telehealth",
  "Remote monitoring",
  "Wearable sensors",
  "Implantable sensors",
  "Ingestible sensors",
  "Smart pills",
  "Digital pills",
  "Connected pills",
  "Medication reminders",
  "Pill dispensers",
  "Medication tracking",
  "Adherence monitoring",
  "Compliance tracking",
  "Outcome measurement",
  "Quality metrics",
  "Performance indicators",
  "Key performance indicators",
  "Success metrics",
  "ROI measurement",
  "Cost-benefit analysis",
  "Break-even analysis",
  "Sensitivity analysis",
  "Scenario analysis",
  "Monte Carlo simulation",
  "Risk assessment",
  "Risk management",
  "Risk mitigation",
  "Risk transfer",
  "Risk sharing",
  "Risk pooling",
  "Risk diversification",
  "Risk hedging",
  "Risk insurance",
  "Risk bonds",
  "Catastrophe bonds",
  "Weather derivatives",
  "Commodity futures",
  "Currency futures",
  "Interest rate futures",
  "Stock index futures",
  "Options contracts",
  "Call options",
  "Put options",
  "American options",
  "European options",
  "Asian options",
  "Barrier options",
  "Binary options",
  "Digital options",
  "Vanilla options",
  "Exotic options",
  "Structured products",
  "Collateralized debt obligations",
  "CDOs",
  "Mortgage-backed securities",
  "MBS",
  "Asset-backed securities",
  "ABS",
  "Collateralized loan obligations",
  "CLOs",
  "Credit default swaps",
  "CDS",
  "Interest rate swaps",
  "Currency swaps",
  "Commodity swaps",
  "Equity swaps",
  "Total return swaps",
  "Basis swaps",
  "Inflation swaps",
  "Volatility swaps",
  "Variance swaps",
  "Correlation swaps",
  "Dispersion swaps",
  "Dividend swaps",
  "Earnings swaps",
  "GDP swaps",
  "Weather swaps",
  "Catastrophe swaps",
  "Longevity swaps",
  "Mortality swaps",
  "Life expectancy swaps",
  "Annuity swaps",
  "Pension swaps",
  "Liability swaps",
  "Asset swaps",
  "Portfolio swaps",
  "Index swaps",
  "Basket swaps",
  "Tranche swaps",
  "Mezzanine swaps",
  "Senior swaps",
  "Junior swaps",
  "Subordinate swaps",
  "Super senior swaps",
  "First loss swaps",
  "Second loss swaps",
  "Third loss swaps",
  "Fourth loss swaps",
  "Fifth loss swaps",
  "Sixth loss swaps",
  "Seventh loss swaps",
  "Eighth loss swaps",
  "Ninth loss swaps",
  "Tenth loss swaps",
  "Nth loss swaps",
  "Pro rata swaps",
  "Sequential swaps",
  "Planned amortization swaps",
  "PAC swaps",
  "Targeted amortization swaps",
  "TAC swaps",
  "Support swaps",
  "Companion swaps",
  "Z-bond swaps",
  "Accrual swaps",
  "Inverse floaters",
  "IO strips",
  "PO strips",
  "CMO tranches",
  "REMIC tranches",
  "Grantor trust certificates",
  "Owner trust certificates",
  "Pass-through certificates",
  "Participation certificates",
  "Mortgage participation certificates",
  "MPCs",
  "Real estate mortgage investment conduits",
  "REMICs",
  "Grantor retained annuity trusts",
  "GRATs",
  "Qualified personal residence trusts",
  "QPRTs",
  "Charitable remainder trusts",
  "CRTs",
  "Charitable lead trusts",
  "CLTs",
  "Intentionally defective grantor trusts",
  "IDGTs",
  "Dynasty trusts",
  "Generation-skipping trusts",
  "GSTs",
  "Life insurance trusts",
  "ILITs",
  "Qualified terminable interest property trusts",
  "QTIPs",
  "Bypass trusts",
  "Credit shelter trusts",
  "Marital deduction trusts",
  "A/B trusts",
  "A/B/C trusts",
  "A/B/C/D trusts",
  "A/B/C/D/E trusts",
  "A/B/C/D/E/F trusts",
  "A/B/C/D/E/F/G trusts",
  "A/B/C/D/E/F/G/H trusts",
  "A/B/C/D/E/F/G/H/I trusts",
  "A/B/C/D/E/F/G/H/I/J trusts",
  "A/B/C/D/E/F/G/H/I/J/K trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X/Y trusts",
  "A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X/Y/Z trusts"
];
