theme: jekyll-theme-dinky
title: JPMC Workers Alliance
description: >
    <p>This is the Official Home Page of the JPMC Workers Alliance.</p>
    <p>
    We are a dedicated, coordinated team of ground-level JPMC employees devoted to a simple mission:
    Better working conditions, pay, and benefits for all non-management JPMC employees worldwide.
    </p>

