theme: jekyll-theme-dinky
title: JPMC Workers Alliance
description: >
    The Official Github Page of the JPMC Workers Alliance.
    
    We're a dedicated, coordinated team of ground-level JPMC employees devoted to a simple mission:
    Better working conditions, pay, and benefits for all non-management JPMC employees worldwide.


