theme: jekyll-theme-dinky
title: JPMC Workers
description: >
    <p>
    We are a dedicated team of JPMC employees devoted to a simple mission:
    Better working conditions for all JPMC employees worldwide.
    </p>

