theme: jekyll-theme-dinky
title: JPMC Workers
description: "We are a dedicated team of JPMC employees devoted to a simple mission: Better working conditions for all JPMC employees worldwide."
baseurl: ""  # This ensures no subdirectory
url: "https://jpmcWorkers.github.io"  # Your actual GitHub Pages domain

