name: Link Validation Tests (DISABLED)

on:
  # Disabled - uncomment to re-enable
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  # schedule:
  #   # Run tests daily at 6 AM UTC to catch broken external links
  #   - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  link-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build the site
      run: npm run build
    
    - name: Run Playwright link validation tests
      run: npm run test
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Comment PR with test results
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Link validation tests failed. Please check the [test report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
          })

  # Separate job for external link checking (more tolerant of failures)
  external-link-check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build the site
      run: npm run build
    
    - name: Check external links with markdown-link-check
      run: |
        npm install -g markdown-link-check
        find . -name "*.md" -not -path "./node_modules/*" -exec markdown-link-check {} \; || true
        
    - name: Check external links in built HTML
      run: |
        npm install -g broken-link-checker
        npx astro preview &
        sleep 10
        blc http://localhost:4321/workers.github.io -ro --filter-level 2 || true
